### ISSUE TITLE
Replace QNConverters with functions from the io.xml module

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#122]
With the introduction of `Particle`, there's no need to convert quantum numbers (see e.g. https://github.com/ComPWA/expertsystem/pull/110/commits/ef3efeb0ca6326f95b2c797597751194cbe6a842).

Best step-by-step procedure (fixing all related issues per step):
- [x] Remove `AbstractQNConverter.parse_from_dict`
- [ ] Remove `AbstractQNConverter.convert_to_dict`
- [ ] Remove `AbstractQNConverter`

**Comment by spflueger** [comment]
Sounds good, I think it would make sense to have a `to_dict` function in the spin class and just reuse that in the io dumping code
