### ISSUE TITLE
Remove MeasuredValue class

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#123]
Remove class `MeasuredValue`
https://github.com/ComPWA/expertsystem/blob/4c9936b8efdade3f3d97622f866596f54e4a7f61/expertsystem/data.py#L74-L91

This class was introduced to retain the error of a value in the particle list (mass and width), but information of the uncertainty in a mass or width is not used by the expertsystem. So mass and width can just become `float` instead of `MeasuredValue`.

**Comment by redeboer** [comment]
Not that we are trying to remove the concept of a 'fit parameter' from the particle list entirely. This will come into play later when designing a recipe file module (#22) that does contain fit parameters.

**Comment by spflueger** [comment]
Removing the concept of a fit parameter from the expert system makes sense. I'm not sure about removing info about some parameters like mass and width. They are not used in the expert system, but they could be used later on in tensorwaves. Hence it would not really hurt to take those values along (since the expert system will also serve as an interface for tensorwaves)

**Comment by redeboer** [comment]
Concretely, what happens now is: some mass and value definition in the `particle_list.xml/yaml` contain an `Error` along with a `Value` (and some only a `Value`). I assume the `Error` is the uncertainty reported by the PDG. The `expertsystem` needs a `Value` only (`float`), not the `Error`. And I doubt that there's any use case of using the uncertainty reported by the PDG in `tensorwaves`. If there is, that 'parameter uncertainty' should be inserted later on, not at the starting point of the `expertsystem` (i.e. the particle list).

**Comment by spflueger** [comment]
> Concretely, what happens now is: some mass and value definitions in the `particle_list.xml/yaml` contain an `Error` along with a `Value` (and some only a `Value`). I assume the `Error` is the uncertainty reported by the PDG. The `expertsystem` needs a `Value` only (`float`), not the `Error`. And I doubt that there's any use case of using the uncertainty reported by the PDG in `tensorwaves`, let's say as some 'fit parameter uncertainty'. If there is, that 'parameter uncertainty' should be inserted later on, not at the starting point of the `expertsystem` (i.e. the particle list).

Right. But I imagine this to become less transparent, in the sense that it will be hard to see where that error info would enter the picture. It would be much easier to track if it was just attached to that variable from the beginning on (since they belong together)

**Comment by redeboer** [comment]
The term variable is where the confusion arises. Mass and Width are just values that the expert system uses for mass conservations checks -- these are not variable. It's only later that these mass and width values are plugged into the parameter list as initial values for the pole positions (confusingly called mass of the resonance). So I think we should keep that strictly separated.

**Comment by spflueger** [comment]
I'm not sure I can follow. Like I said initially, I agree on using just values in the expert system and not "parameter/fit parameter". The thing im unsure about is whether to remove the error of those values, as they might be used later on in tensorwaves. And adding those values in at a later point is probably a really confusing concept.

**Comment by redeboer** [comment]
> whether to remove the error of those values, as they might be used later on in tensorwaves

In what way? Theoretically they can be used for Minuit. But does that mean they have to be inserted all the way from the starting point of the expertsystem? I think that would be confusing, because it's unclear why those `Error` values are there at that stage.

**Comment by redeboer** [comment]
To be sure, removing `MeasuredValue` would simplify the structure of the `Particle` class
https://github.com/ComPWA/expertsystem/blob/4c9936b8efdade3f3d97622f866596f54e4a7f61/tests/io/test_particle_collection.py#L23-L33
and the readability of the particle list section
https://github.com/ComPWA/expertsystem/blob/4c9936b8efdade3f3d97622f866596f54e4a7f61/tests/amplitude/expected_recipe.yml#L1278

**Comment by spflueger** [comment]
>In what way? Theoretically they can be used for Minuit. But does that mean they have to be inserted all the way from the starting point of the expertsystem and carried on to the recipe file where they might be used eventually? I think that would be confusing, because it's unclear why those Error values are propagated through the expertsystem itself.

But the particle class will later be the interface for tensorwaves right?

Maybe I ask the question this way: Can you show me some example code on how you imagine the workflow for the errors to look like at the end? This is the part I'm unsure about

**Comment by redeboer** [comment]
> But the particle class will later be the interface for tensorwaves right?

`tensorwaves` doesn't really use the `Particle` class, apart from `Spin` info maybe

> Can you show me some example code on how you imagine the workflow for the errors to look like at the end?

Not really, because we don't have that functionality in `tensorwaves`. But I think an error should be part of a fit paramater class and that only comes into play when the recipe is created.
