### ISSUE TITLE
Rename StateTransitionGraph to FeynmanGraph

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#133]
The `expertsystem` uses a slightly unusual definition of a graph:
1. the edges hold info, not the nodes
2. all graphs have open ends (initial and final state)

This is because the graph is similar to how we draw a Feynman graph. We should therefore rename `StateTransitionGraph` and its related class in terms of Feynman graph concepts.

**Comment by spflueger** [comment]
I see your reasoning, but I intentionally avoided to use this name to not confuse physicists since it is not an actual Feynman graph.  It just uses some concepts from Feynman graphs.

**Comment by redeboer** [comment]
Okay, makes sense. But then, can the design be made into something that can be accurately called a Feynman diagram?

**Comment by redeboer** [comment]
Well let's keep this in mind while #127 is further resolved in a PR. This is a tricky issue indeed because of what Feynman diagrams represent mathematically.

**Comment by redeboer** [comment]
After all the refactoring, the name `StateTransitionGraph` makes more sense, so let's close this issue.
