### ISSUE TITLE
Change ComplexEnergy class into decorator

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#157]
Since #153

> I will try to work with a class decorator here.
> ```python3
> @ComplexEnergy
> class ComplexEnergyState():
> ...
> ```
> Maybe that can resolve all our issues here
> 
_Originally posted by @spflueger in https://github.com/ComPWA/expertsystem/timeline_

**Comment by spflueger** [comment]
Due to refactoring this issue is no longer valid, hence resolved.
