### ISSUE TITLE
Implement pytest fixtures where possible

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#185]
Test discovery is currently slow, because there are several duplicate calls, such as `load_default_particle_list`. This can be improved with [fixtures](https://docs.pytest.org/en/latest/example/special.html).

See also https://github.com/ComPWA/tensorwaves/issues/96

**Comment by redeboer** [comment]
Here's another reason why we need fixtures:
https://github.com/ComPWA/expertsystem/pull/202/checks?check_run_id=981306082

Somehow, one of the tests changes `DATABASE` back into a nested `dict`, which is then again used by another test that expects it to be a `ParticleCollection`.

**Comment by spflueger** [comment]
yeah, I already implemented this
