### ISSUE TITLE
Decide whether to choose a convention for parity of fermions

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#199]
This issue came up while working on #190, where PDG info is imported from the scikit-hep/particle package into Particle instances. That package leaves parity undefined for leptons , which led us to reconsider our current 'source of truth', particle_list.yml (see also #189). That list indeed defines parity as +1 for fermions, -1 for anti-fermions.

Purely in technical terms, we now need to either (1) let the PDG adapter attribute +1 parity to fermion Particle instances or (2) leave parity undefined in Particle fermions and attribute the parity once particle properties are propagated through the StateTransitionGraphs.

See also https://github.com/ComPWA/expertsystem/pull/181#issuecomment-670602932

**Comment by wgradl** [comment]
Hi all,

I don't understand the comment that parity is not well-defined for
leptons.

leptons _do_ have intrinsic parity.  From general principles,
fundamental fermions and their fundamental anti-fermions have opposite
intrinsic parity.  By convention, one takes P(fermion) = +1, hence
P(anti-fermion) = -1.  So, an electron has even parity, a positron has
odd parity.

Maybe I misunderstand the issue?

Cheers,  W.


> @spflueger This needs to be reformulated
> 
> See
> https://github.com/ComPWA/expertsystem/pull/181#issuecomment-670602932
> 
> Our existing `particle_list.yml` has parities defined for leptons, which is strictly speaking incorrect. But removing these values might destroy lepton checks.
> 
> This touches on several issues, also _CP_-conservation.
> 

-- 
Prof Dr Wolfgang Gradl        University of Mainz 
BES-III, BABAR & A2@MAMI      Institut für Kernphysik
Tel. +49-6131-39-25871

**Comment by redeboer** [comment]
Hi @wgradl, thanks a lot for your thougts! This feedback is important, because the [`Particle`](https://pwa.readthedocs.io/projects/expertsystem/en/0.3.0-alpha/api/expertsystem.data.html#expertsystem.data.Particle) class serves as a public interface and is the starting point when using the `expertsystem`.

This issue came up while working on #190, where PDG info is imported from the [scikit-hep/particle](https://github.com/scikit-hep/particle) package into `Particle` instances. That package leaves parity undefined for leptons , which led us to reconsider our current 'source of truth', [`particle_list.yml`](https://github.com/ComPWA/expertsystem/blob/8b5c257c6738d3e50ff1d56a7a06714e3e2a7036/tests/io/test_particle_collection.py) (see also #189). That list indeed defines parity as +1 for fermions, -1 for anti-fermions.

Purely in technical terms, we now need to either (1) let the PDG adapter attribute +1 parity to fermion `Particle` instances or (2) leave parity undefined in `Particle` fermions and attribute the parity once particle properties are propagated through the `StateTransitionGraph`s.

**Comment by spflueger** [comment]
Yeah, so this question boils down to:
Do we want to choose a convention e.g P(fermion) = 1 or do we work without conventions? A rather technical question. In principle it would be best to work without a conventions so the user has full control over that.
