### ISSUE TITLE
Refactor the expert system

### ISSUE THREAD

**Issue by spflueger** [ComPWA/expertsystem#2]
- [x] Apply black formatting https://github.com/ComPWA/tensorwaves/pull/49 --> https://github.com/ComPWA/expertsystem/pull/18
- [ ] Implement [`Particle`](https://pypi.org/project/Particle/) package
- [ ] Hide or reorganise implementation details.
- [ ] Create `Recipe` object (?)
- [ ] Decouple internals from XML structure
- [ ] Move the `StateTransitionManager` higher up. A statement like `from tensorwaves.expertsystem.ui.system_control import StateTransitionManager` is unnecessarily verbose because the `StateTransitionManager` is almost the only thing you need to work with the expert system.

See also:
- https://github.com/ComPWA/tensorwaves/issues/29
- https://github.com/ComPWA/pycompwa/issues/34
- https://github.com/ComPWA/pycompwa/issues/39
- https://github.com/ComPWA/pycompwa/issues/29

**Comment by redeboer** [comment]
This issue is too large, more like a milestone, and has to be split up in separate issues.
