### ISSUE TITLE
Check consistency of particle definitions

### ISSUE THREAD

**Issue by spflueger** [ComPWA/expertsystem#205]
Use Gellmann Nishijima Rule and perhaps more to verify particles are defined consistently and immediately pick up wrong definitions

**Comment by redeboer** [comment]
c0abac05fc3d50bb638f079dc77bd600e1d3e227 of #202 implements a check on Gell-Mann–Nishijima.

Do we need more? If so, this should become an epic. Then #200 can become part of this epic.
