### ISSUE TITLE
Automate or facilitate changelogs/release notes

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#221]
The release notes are currently done by hand
https://github.com/ComPWA/expertsystem/releases
but this info could (in theory) be extracted from the linear commit history and conventional commit messages.

**Comment by spflueger** [comment]
Yeah, I had the same idea when I wrote that last release description. I guess we need a combination of both things. One being a detailed list of all commits and its changes, but also summary of changes on top in terms of a larger feature that was tackled.

Also we have to be really precise in the labeling of the commit messages, to be able to pick out bugfix, features, and interface changing commits with high accuracy.

**Comment by redeboer** [comment]
One thing that's interesting to experiment with is `git shortlog`. But well, there must be tools that integrate better with GitHub itself.
