### ISSUE TITLE
Improve readability of JPsi to gamma pi0 pi0 test

### ISSUE THREAD

**Issue by spflueger** [ComPWA/expertsystem#232]
The total number of found solutions is 48. It would be good to do a little bit more fined grained testing of the solutions. This would improve the quality of the test and also make it easier to understand.

So the amount of 48 totals up in the following way (note that a total of two f0, two f2 and one omega state are included):
* each f0 intermediate state creates 4 solutions -> 2*4 = **8**
* each f2 intermediate state creates 12 solutions -> 2*12 = **24**
* the omega state creates 8 solutions. **But** identical particle combinatorics increases this by a factor of 2 (swapping the two pi0s). ->  2*8 = **16**

-> 8 + 24 + 16 = 48

I propose to test for the amount of f0, f2 and omega solutions separately

**Comment by redeboer** [comment]
@spflueger can this issue be closed? See
https://github.com/ComPWA/expertsystem/blob/589cb9bcd861300144851b6cfdcb3cbe1573ee73/tests/channels/test_jpsi_to_gamma_pi0_pi0.py#L9-L43

**Comment by spflueger** [comment]
Yep
