### ISSUE TITLE
Separate out XML parser for HelicityAmplitudeGeneratorXML

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#26]
The `HelicityAmplitudeGeneratorXML` currently has too many responsibilities. First step to fix that is to rename it `HelicityAmplitudeGenerator` abstract its `write_to_file` into a `write` function that gets a `parser` as an argument. For now, an XML parser only is sufficient, later another parser can (should! https://github.com/ComPWA/tensorwaves/issues/61) be written for YAML as well.

**Comment by spflueger** [comment]
I think we should use a recipe structure that is produces the same dictionary structure in python independent of the file format (xml, yaml, json...)
More precisely this means we have to get rid of attributes and changed them into tags. The (example recipe file)[https://github.com/ComPWA/tensorwaves/blob/master/examples/intensity-recipe.yaml] from tensorwaves should be the example for xml to follow as well.

**Comment by redeboer** [comment]
> I think we should use a recipe structure that is produces the same dictionary structure in python independent of the file format (xml, yaml, json...)

https://github.com/ComPWA/expertsystem/issues/22
