### ISSUE TITLE
Implement check for all violations in a reaction

### ISSUE THREAD

**Issue by spflueger** [ComPWA/expertsystem#281]
A new function that can check for all violated rules is needed. I propose the form 
```python3 
check_violations(initial_state, final_state, interaction_type: Optional[InteractionTypes]) -> List[str]
```

Before the `FullPropagator` also had this responsibility of finding all violations. This functionality has to be re-implemented here. Concretely an additional managing layer on top of the csp solver is needed. There are two options (I favor option 1):

1. A new approach would be to always use all rules and individually check each rule which graph they violate. Then by looking at the results of each rule the violation can be accurately determined. If the user requested a specific interaction, the violated rules can be filtered for that specific interaction.
2. Previously it was iteration on the temporary result until there are no more violations. This iteration is required due to early stopping of the solvers if there are violations. The following already implements this (it just has to be adapted a bit)

```python3
        def __determine_all_violations(
            self, current_result: Result, graph_settings: GraphSettings
        ) -> Result:
            # Unfortunately the csp constraint module will jump out of the
            # solving process one a rule violates all possibilities.
            # In order to find all violations a recursing with csp is needed.
            # A simple validation will not suffice, because some node quantum
            # numbers may not be set by the user. So they have to be generated
            # by the system.
            # Stop rerun once the set of not_executed_rules does not change
            # or is empty. Then just finish up with validation
            # solver = CSPSolver(self.__allowed_intermediate_particles)
            previous_result = Result([])
            violated_rules = current_result.violated_rules
            while (
                previous_result.not_executed_rules
                != current_result.not_executed_rules
                and current_result.not_executed_rules
            ):
                previous_result = current_result
                for (
                    node_id,
                    node_setting,
                ) in graph_settings.node_settings.items():
                    node_setting.conservation_rules = (
                        current_result.not_executed_rules[node_id]
                    )
                current_result = self.__run_csp(self.__graph, graph_settings)
                for node_id, rule_set in current_result.violated_rules.items():
                    violated_rules[node_id].update(rule_set)

            validated_result = validate_fully_initialized_graph(
                self.__graph, current_result.not_executed_rules
            )
            for (
                node_id,
                rule_set,
            ) in validated_result.violated_rules.items():
                violated_rules[node_id].update(rule_set)

            return Result(
                [], validated_result.not_executed_rules, violated_rules
            )
```

**Comment by redeboer** [comment]
See also commented parts in the `test_nbody_reactions.py`:
https://github.com/ComPWA/expertsystem/blob/603b0b568cae18ec3ca35752a64ec0f2930e5bca/tests/channels/test_nbody_reactions.py#L37-L49

https://github.com/ComPWA/expertsystem/blob/603b0b568cae18ec3ca35752a64ec0f2930e5bca/tests/channels/test_nbody_reactions.py#L52-L55

https://github.com/ComPWA/expertsystem/blob/603b0b568cae18ec3ca35752a64ec0f2930e5bca/tests/channels/test_nbody_reactions.py#L79-L86

**Comment by spflueger** [comment]
In order to find violations for a given reaction the unknown graph elements (edges and nodes) in between the initial and final state have to be filled with information. Otherwise the rules cannot process the case as information is missing. That means we first have to fill in the blanks with possible values -> run `CSPSolver`. Also note that a lot of rules can only work reliably with only two body inputs, e.g. the Parity conservations or Spin couplings. Therefore it would be best to create isobar topologies for the given problem. Solving such problems is rather time consuming though.
**Generally having a real expertsystem with rules that can create new facts instead of just returning a bool would be the optimal solution, as it can handle C and G parity conservation much easier and also has a speed benefit. However for now we could find a compromise and create a violation checker that does not guarantee to find all violations. That would be the goal for this PR.**

**As for the two options. I prefer option 1 with the combination of restricting things to a n body interaction node.** Then only L and S quantum numbers have to be assigned to the node. For each of these reaction instances it is possible to keep track of which which rules are passing. That allows to get all of the violations and also violations that involve several connected rules to create the violation as a unit. Also the least restricting case should be the result that is returned.
