### ISSUE TITLE
Avoid deepcopy of StateTransitionGraph

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#310]
We currently use `deepcopy` to clone a `StateTransitionGraph`, but this creates several identical `Particle` instances.

**Comment by spflueger** [comment]
Ok, so the function which performs deep copies extensively is the merging of the solutions of the solving module with the initial graph `solving._merge_solutions_with_graph()`. The key is that we do not need `deepcopy`, to all levels but only a copy of the graph and the containers `nodes`, `edges`, `node_props`, `edge_props`. The contents do not have to be copied. This can be achieved nicely be overwriting the `__copy__` or `__deepcopy__` functions.

**Comment by redeboer** [comment]
Ok I added this issue to the release milestone, sounds like it can be handled within that already.
