### ISSUE TITLE
Decide on minimal Python version

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#37]
The framework is currently tested for Python 3.5-3.7, while setup requirements are >=3.3 and the conda environment file requires python >=3.5. There seems to be no clear reasoning here.

> Hmm, I think we probably want python 3.6 or so. @redeboer Why was 3.5 introduced here? f-strings are python 3.6.

_Originally posted by @spflueger in https://github.com/ComPWA/expertsystem/pull/34_

**Comment by spflueger** [comment]
I would go for python 3.6. Then we have for example f-strings. Also the from the first release and end of lifetime infos https://www.python.org/downloads/ I think 3.6 is a good choice.
