### ISSUE TITLE
Remove Type from FitParameters

### ISSUE THREAD

**Issue by spflueger** [ComPWA/expertsystem#397]
Currently there is a Type attribute attached to `FitParameter`s in the `AmplitudeModel`. These are remnants of the old c++ code and it should verified if there is any merit in keeping them.

A type could be useful for definition of a complex valued Parameter:  Magnitude + Phase  or  Real + Imaginary (see https://github.com/ComPWA/tensorwaves/issues/161)

**Comment by redeboer** [comment]
> A type could be useful for definition of a complex valued Parameter: Magnitude + Phase or Real + Imaginary (see ComPWA/tensorwaves#161)

This can be handled more easily when #384 is through. One can then start to define different types of `FitParameter` as `attr.s` classes with an inheritance hierarchy similar to the dynamics. With `attr.asdict` it's then easy to dump those `FitParameter` to a `dict` and add a `"type": <class name>`, just like is done for `Dynamics` classes.
