### ISSUE TITLE
Isolate XML keys to a separate submodule

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#4]
Currently, all modules of the expert system have some dependency on `xmltodict`, see for example [here](https://github.com/ComPWA/pycompwa/blob/39d8ecd8c1bd756184bd52495cd5b212e8bcf810/pycompwa/expertsystem/state/particle.py#L24). Would be better to rewrite this into general interfaces and have specifications for XML separated out.

**Comment by spflueger** [comment]
As mentioned in #25, I'm missing the big picture. Separating the xml related things into a module is not bad, but I think we can even do one better.
I would like to have all xml (or other file format) related code to vanish completely.
Similar to the current code a single dict (with a defined structure) contains all of the information. This can be written or read from file in various file formats, as long as they are compatible with the dictionary structure.

**Comment by redeboer** [comment]
Alright, let's move this discussion to a separate design document separate out more focused issues from that.
