### ISSUE TITLE
Parity violation in weak decays is not considered in coupling of amplitudes

### ISSUE THREAD

**Issue by sebastianJaeger** [ComPWA/expertsystem#419]
When generating an Amplitude Model for the decay Lambda_c^+ -> proton K- pi+, the magnitudes and phases of weak decays are automatically coupled due to parity, although parity violation in weak decays means that they should be independent of each other. 

For example in the subdecay Lambda_c^+ -> proton K*(892), the parameter
```python
"Magnitude_Lambda(c)+_to_K*(892)0_1+p_0.5;K*(892)0_to_K-_0+pi+_0"
```
gets used in both the 
```python
"Lambda(c)+_-0.5_to_K*(892)0_-1+p_-0.5;K*(892)0_-1_to_K-_0+pi+_0"
```
and the
```python
"Lambda(c)+_-0.5_to_K*(892)0_1+p_0.5;K*(892)0_1_to_K-_0+pi+_0"
```
amplitude, though these should be independend of each other.

**Comment by spflueger** [comment]
@sebastianJaeger Thanks for the bug report!
A tip for the report itself: You can selected the type of issue in the `Labels` section on the right -> `Bug` (instead of putting it into the title)

**Comment by redeboer** [comment]
> instead of putting it into the title

That tag in the title is set by the issue template
https://github.com/ComPWA/expertsystem/blob/0.6.5/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by redeboer** [comment]
> When generating an Amplitude Model for the decay Lambda_c^+ -> proton K- pi+, the magnitudes and phases of weak decays are automatically coupled due to parity, although parity violation in weak decays means that they should be independent of each other.
> 
> For example in the subdecay Lambda_c^+ -> proton K*(892), the parameter
> 
> ```python
> "Magnitude_Lambda(c)+_to_K*(892)0_1+p_0.5;K*(892)0_to_K-_0+pi+_0"
> ```
> 
> gets used in both the
> 
> ```python
> "Lambda(c)+_-0.5_to_K*(892)0_-1+p_-0.5;K*(892)0_-1_to_K-_0+pi+_0"
> ```
> 
> and the
> 
> ```python
> "Lambda(c)+_-0.5_to_K*(892)0_1+p_0.5;K*(892)0_1_to_K-_0+pi+_0"
> ```
> 
> amplitude, though these should be independend of each other.

So just for my understanding, what should be the names in this case?
