### ISSUE TITLE
Allow inserting custom dynamics

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#440]
Since #434, it has become possible to do something like:
```python
@attr.s
class CustomDynamics(Dynamics):
    par1: FitParameter = attr.ib()
    par2: FitParameter = attr.ib()
    ...

custom_dynamics = CustomDynamics(...)
# model: AmplitudeModel
model.dynamics["J/psi(1S)"] = custom_dynamics
```
without breaking `asdict` and `fromdict` (since #436) and also inserting `par1` and `par2` into `model.parameters` (the `FitParameters` class that keeps track of which `FitParameter`s are in the `AmplitudeModel`. There's at least one bug though: if `"J/psi(1S)"` was already assigned some `Dynamics` instance with `FitParameter`s, the old `FitParameter`s are still in `model.parameters`. So the `FitParameters` class has to become mutable (see also #382).

Other bugs may be pointed out as well once tests are written and the procedure illustrated in the notebooks.

**Comment by spflueger** [comment]
Is overhauled by PR #454
