### ISSUE TITLE
Modulate the amplitude module

### ISSUE THREAD

**Issue by spflueger** [ComPWA/expertsystem#65]
- [x] Move write functionality to the `io` module: the `io` module just dumps those python classes to a file format of your choice.
- [x] Formulate the amplitude model in terms of python classes
- [x] (?) Remove `AbstractAmplitudeGenerator` in favour of functions, because the only remaining abstract method is `generate`.

**Comment by redeboer** [comment]
I still don't think nested `dict`s are the way to go, especially after having gone through the [horror of creating a differently shaped nested dict from that](#59) and having to debug it.

Instead, I would prefer an object-oriented approach, such as a base class that represents a component and then derived from that an intensity/amplitude object that can then be further derived into `CoherentIntensity`, `IncoherentIntensity`, etc... Fixes the data throughout the framework, reveals intention (readability!), much easier to debug, and allows for tab completion (not unimportant for the DX).

**Comment by spflueger** [comment]
> I still don't think nested `dict`s are the way to go, especially after having gone through the [horror of creating a differently shaped nested dict from that](#59) and having to debug it.
>
> Instead, I would prefer an object-oriented approach, such as a base class that represents a component and then derived from that an intensity/amplitude object that can then be further derived into `CoherentIntensity`, `IncoherentIntensity`, etc... Fixes the data throughout the framework, reveals intention (readability!), much easier to debug, and allows for tab completion (not unimportant for the DX).

I'm not sure we are talking about the same thing. I'm simply referring to the output to a file. I think all tools for various formats are working based on dicts (xmltodict, json, yaml..). So you are bound to use dicts at this point. Hence I simply want the amplitude generators to output a dict, which can be plugged into a tool of choice and dumped to file. I don't see how and OO class design is of any help here. How that dict is created from the solution, that's another topic.

**Comment by redeboer** [comment]
It's still related, I think. What I mean is that the amplitude model should be created in an OO way (see [my description](https://github.com/ComPWA/expertsystem/issues/65#issuecomment-645464081)), while the output is separated from that. So only at the latest point (the output stage), there is an adapter that converts the amplitude model (which is built up of intensity objects) to a nested dictionary that can then be immediately dumped to YAML or whatever format. Then you have confined the representation to a separate place and you can change it at any stage without having to touch the amplitude model builder or whatever modules come before that.

You can even make that dump-to-dict module fancier at some stage, like integrating it with JSON validations schemes. Key point is, there's a boundary between representation in a file format (formulated in terms of a nested `dict`) and the actual amplitude model building.

**Comment by spflueger** [comment]
> there is an adapter that converts the amplitude model (which is built up of intensity objects) to a nested dictionary that can then be immediately dumped to YAML or whatever format.

Yeah I was just talking about the latter part. So the dumping out into a file. I suggested to put this dumping code out of the AmplitudeGenerator, and have this instead generate a dictionary.

Or am I missing something here?
