### ISSUE TITLE
Standardize and automate release flow

### ISSUE THREAD

**Issue by redeboer** [ComPWA/expertsystem#68]
## Problem description

Have had a few times that pushing a tag results in a failed deploy job, e.g. https://travis-ci.com/github/ComPWA/expertsystem/jobs/350476070, because I forgot to bump the version in the `setup.py` file. There are better tools for that, like [`bumpversion`](https://pypi.org/project/bumpversion/).

Also, we haven't really thought about how to deal with releases. Linear commit history already provides some sort of clean versioning, now it's just a matter of summarising the most important changes for each release. For now, I follow the [release style that tensorflow uses](https://github.com/tensorflow/tensorflow/releases). Although we're unclear about [Semantic Versioning](https://semver.org/).

## Summary
* Should we use [Semantic Versioning](https://semver.org/)?
* How to decide about whether a release is a patch or a minor version update?
* How to make that as effortless (automatic) as possible?
* Which (https://github.com/ComPWA/expertsystem/pull/70) conventions to use for the release draft?
* How to keep Git tags in sync with the (single source of truth)
* Should we reconsider our packaging tool/setup (i.e.`setup.cfg`, `pyproject.toml`, ...)

This differs from https://github.com/ComPWA/expertsystem/pull/70 in the sense that in this repository we want to try out and illustrate some tools for a nice release flow. In the PWA Pages we describe that release flow after it turns out to work well. The PWA Pages then serve more as a guideline.

## Some resources
- https://packaging.python.org/guides/single-sourcing-package-version/
- https://semver.org/
- https://stackoverflow.com/a/5582128 (on Git and single source of truth for package version)

**Comment by spflueger** [comment]
Regarding the version of setup.py: The current situation is not ideal, but its fairly ok. Not sure if bumpversion is foolproof. Some kind of hook in github would almost be best, that has access to the tag stage and will deny a tag if the version does not match. Don't know what state of the art is here.

Regarding the versioning: Semantic versioning is nice and I would love to do that (to get some hands on experience with this). But for me that would imply that you keep several major version branches that are maintained simultaneously. So I think that will add to much workload.

**Comment by spflueger** [comment]
Lets turn this into an ADR, to keep our decision fixed. I think this should almost be ComPWA global, decision...

**Comment by redeboer** [comment]
If it's global, imho the best place would be
https://github.com/ComPWA/PWA-pages
For instance, a section with thoughts on linear commit history (particularly its use in a research settings), how that facilitates the release flow (the linear commit messages neatly summarise changes), how to tag and bump a version (as you say, probably best through a git hook), and how to draft a release note.

**Comment by spflueger** [comment]
Yeah exactly. That was my idea. Do you think this decision should be global or project local?

**Comment by redeboer** [comment]
So a description of the conventions can best be placed in some global place and I can only think of the PWA Pages (even if they're experimental). Git hooks and all have to be implemented for each repo, ofc, but the expertsystem can serve as a nice try-out (particularly with the upcoming pre-releases).

**Comment by spflueger** [comment]
I meant it if the conventions we decide based on the versioning will apply to all subprojects within ComPWA? Also we should keep in mind that tensorwaves will be closely coupled to AmplitTF and zfit.

**Comment by redeboer** [comment]
Maybe 'guideline' is a better word than 'convention' here.
Anyway, main point is: create an ADR under the expertsystem or under the PWA Pages?

**Comment by redeboer** [comment]
Now that #102 is through, I think this issue can be fixed by creating something like a `__version__` file at the `script` stage of the Travis deploy job. That file can then be used in the `setup.cfg` (we have to make sure this doesn't cause errors for users). So the version determination would happen somewhere this stage:
https://github.com/ComPWA/expertsystem/blob/a438784a0e65a5e86e62facd05493936892e1fd1/.travis.yml#L56-L65
And we have to make sure this job is only performed when triggered by a tag.

**Comment by spflueger** [comment]
https://pypi.org/project/setuptools-scm/ this cant help?

**Comment by redeboer** [comment]
Yes good one, looks promising, I'll check it out later.
